[project]
name = "comfy_client"
version = "0.1.0" 
dependencies = [
    "websocket-client",
    "Pillow"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["comfy_client"]
